"""Updated transactions table

Revision ID: 3040814b0375
Revises: 4a543fa981eb
Create Date: 2025-05-20 20:21:31.169092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3040814b0375'
down_revision: Union[str, None] = '4a543fa981eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('sender_account', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('receiver_account', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('sender_country', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('sender_mulicaplity', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('receiver_country', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('receiver_mulicaplity', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('transaction_type', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('notes', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'transactions', ['transaction_id'])
    op.drop_constraint('transactions_customer_id_fkey', 'transactions', type_='foreignkey')
    op.drop_constraint('transactions_bank_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'bank_id')
    op.drop_column('transactions', 'customer_id')
    op.drop_column('transactions', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('bank_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transactions_bank_id_fkey', 'transactions', 'banks', ['bank_id'], ['id'])
    op.create_foreign_key('transactions_customer_id_fkey', 'transactions', 'customers', ['customer_id'], ['id'])
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'receiver_mulicaplity')
    op.drop_column('transactions', 'receiver_country')
    op.drop_column('transactions', 'sender_mulicaplity')
    op.drop_column('transactions', 'sender_country')
    op.drop_column('transactions', 'receiver_account')
    op.drop_column('transactions', 'sender_account')
    op.drop_column('transactions', 'currency')
    op.drop_column('transactions', 'timestamp')
    op.drop_column('transactions', 'transaction_id')
    # ### end Alembic commands ###
