"""Breceiver_municipality rename

Revision ID: 776f7565ff09
Revises: 3040814b0375
Create Date: 2025-05-21 10:35:03.102878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '776f7565ff09'
down_revision: Union[str, None] = '3040814b0375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_municipality', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('receiver_municipality', sa.String(), nullable=False))
    op.drop_column('transactions', 'receiver_mulicaplity')
    op.drop_column('transactions', 'sender_mulicaplity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_mulicaplity', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('receiver_mulicaplity', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'receiver_municipality')
    op.drop_column('transactions', 'sender_municipality')
    # ### end Alembic commands ###
