"""remodell table

Revision ID: 9bae84371bbb
Revises: b3973ea9d17b
Create Date: 2025-05-26 21:33:51.600508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bae84371bbb'
down_revision: Union[str, None] = 'b3973ea9d17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('bankaccount', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'bankaccount')
    # ### end Alembic commands ###
