"""remodell table

Revision ID: bd7c60088bf6
Revises: edf61ec78c61
Create Date: 2025-05-26 20:50:49.548646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7c60088bf6'
down_revision: Union[str, None] = 'edf61ec78c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('personalnumber', sa.String(), nullable=False))
    op.drop_constraint('customers_adress_key', 'customers', type_='unique')
    op.create_unique_constraint(None, 'customers', ['address'])
    op.drop_column('customers', 'adress')
    op.drop_column('customers', 'ssn')
    op.add_column('transactions', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'customer_id')
    op.add_column('customers', sa.Column('ssn', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('adress', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_unique_constraint('customers_adress_key', 'customers', ['adress'], postgresql_nulls_not_distinct=False)
    op.drop_column('customers', 'personalnumber')
    op.drop_column('customers', 'address')
    # ### end Alembic commands ###
