"""remodell table

Revision ID: e0b7c0cea93c
Revises: 9bae84371bbb
Create Date: 2025-05-26 21:36:05.645241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b7c0cea93c'
down_revision: Union[str, None] = '9bae84371bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_address_key', 'customers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('customers_address_key', 'customers', ['address'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
