"""remodell customer table

Revision ID: edf61ec78c61
Revises: c0839a055e0a
Create Date: 2025-05-26 10:46:12.413341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf61ec78c61'
down_revision: Union[str, None] = 'c0839a055e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('adress', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('phone', sa.String(), nullable=False))
    op.drop_constraint('customers_ssn_key', 'customers', type_='unique')
    op.create_unique_constraint(None, 'customers', ['adress'])
    op.drop_column('customers', 'name')
    op.drop_column('customers', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='unique')
    op.create_unique_constraint('customers_ssn_key', 'customers', ['ssn'], postgresql_nulls_not_distinct=False)
    op.drop_column('customers', 'phone')
    op.drop_column('customers', 'adress')
    op.drop_column('customers', 'customer')
    # ### end Alembic commands ###
